services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astral-english-cards-spa
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
